import { renderHook, act } from '@testing-library/react';
import { useInvoices } from '../useInvoices';
import {
  mockUser,
  mockEmployee,
  mockCustomer,
  mockInvoice,
  mockWorkOrder,
} from '../../services/__tests__/testHelpers';
import type { Invoice, InventoryItem, WorkOrder } from '../../../../types';

// Mock dependencies
jest.mock('../../../utils/analytics', () => ({
  trackAction: jest.fn(),
}));

jest.mock('../../../utils/smartNotifications', () => ({
  createInvoiceSentNotification: jest.fn(() => ({ id: 'notif1', message: 'Test' })),
}));

jest.mock('../useInvoiceForm', () => ({
  useInvoiceForm: jest.fn(() => ({
    formData: {
      customerId: 'cust1',
      items: [],
      labor: [],
      vatRate: 21,
      notes: '',
      paymentTerms: '14 dagen',
      issueDate: '2024-01-01',
      dueDate: '2024-01-15',
    },
    errors: {},
    editingInvoiceId: null,
    validate: jest.fn(() => true),
    reset: jest.fn(),
    setFields: jest.fn(),
    setEditingInvoiceId: jest.fn(),
    loadInvoiceForEditing: jest.fn(),
  })),
}));

jest.mock('../../services/invoiceService', () => ({
  createInvoice: jest.fn((data) => ({
    id: 'inv999',
    invoiceNumber: '2024-999',
    ...data,
    status: 'draft',
    timestamps: { created: '2024-01-01T00:00:00.000Z' },
    history: [],
  })),
  updateInvoice: jest.fn((id, data, existing) => ({
    ...existing,
    ...data,
  })),
  updateInvoiceStatus: jest.fn((invoice, status) => ({
    ...invoice,
    status,
  })),
  deleteInvoice: jest.fn((id, invoices) => invoices.filter((inv: Invoice) => inv.id !== id)),
  cloneInvoice: jest.fn((invoice) => ({
    ...invoice,
    id: 'inv999',
    invoiceNumber: '2024-999',
    status: 'draft',
  })),
  syncInvoiceToWorkOrder: jest.fn((invoice, workOrder) => ({
    ...workOrder,
    estimatedHours: 5,
  })),
  sendInvoiceReminder: jest.fn((invoice) => ({
    ...invoice,
    reminders: {
      ...invoice.reminders,
      reminder1Sent: true,
    },
  })),
  shouldShowValidationModal: jest.fn(() => false),
}));

jest.mock('../../utils/helpers', () => ({
  isAutoGeneratedInvoice: jest.fn(() => false),
  createHistoryEntry: jest.fn(() => ({
    type: 'invoice',
    action: 'created',
    message: 'Test',
    timestamp: '2024-01-01T00:00:00.000Z',
  })),
  getEmployeeName: jest.fn(() => 'Test Employee'),
}));

describe('useInvoices', () => {
  const mockInventory: InventoryItem[] = [];
  const mockInvoices: Invoice[] = [mockInvoice];
  const mockWorkOrders: WorkOrder[] = [mockWorkOrder];

  const mockSetInvoices = jest.fn();
  const mockSetWorkOrders = jest.fn();
  const mockSetNotifications = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
    // Mock window methods
    global.alert = jest.fn();
    global.confirm = jest.fn(() => true);
  });

  it('should initialize with default state', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    expect(result.current.showInvoiceForm).toBe(false);
    expect(result.current.showCloneInvoiceModal).toBe(false);
    expect(result.current.showInvoiceValidationModal).toBe(false);
    expect(result.current.invoiceToValidate).toBe(null);
  });

  it('should open invoice form', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    act(() => {
      result.current.setShowInvoiceForm(true);
    });

    expect(result.current.showInvoiceForm).toBe(true);
  });

  it('should edit an invoice', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    act(() => {
      result.current.editInvoice(mockInvoice.id);
    });

    expect(result.current.showInvoiceForm).toBe(true);
  });

  it('should update invoice status', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    act(() => {
      result.current.updateInvoiceStatus(mockInvoice.id, 'sent');
    });

    expect(mockSetInvoices).toHaveBeenCalled();
  });

  it('should delete an invoice', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    act(() => {
      result.current.deleteInvoice(mockInvoice.id);
    });

    expect(mockSetInvoices).toHaveBeenCalled();
  });

  it('should clone an invoice', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    act(() => {
      result.current.cloneInvoice(mockInvoice.id);
    });

    expect(result.current.showCloneInvoiceModal).toBe(true);
  });

  it('should set validation checklist', () => {
    const { result } = renderHook(() =>
      useInvoices(
        mockInvoices,
        mockSetInvoices,
        mockInventory,
        [mockCustomer],
        mockUser,
        mockWorkOrders,
        mockSetWorkOrders,
        mockSetNotifications
      )
    );

    act(() => {
      result.current.setValidationChecklist({
        hoursChecked: true,
        materialsChecked: true,
        extraWorkAdded: false,
      });
    });

    expect(result.current.validationChecklist.hoursChecked).toBe(true);
    expect(result.current.validationChecklist.materialsChecked).toBe(true);
    expect(result.current.validationChecklist.extraWorkAdded).toBe(false);
  });
});



